### ISSUE TITLE
"Trigger Direct Call" action type supports wrong `event`

### ISSUE THREAD

**Issue by yuhui** [adobe/reactor-extension-core#38]
The "Trigger Direct Call" action type (see #23) allows `_satellite.track()` to be triggered without writing custom code.

### Expected Behaviour

https://experienceleague.adobe.com/docs/experience-platform/tags/client-side/satellite-object.html?lang=en

### Actual Behaviour
The "Trigger Direct Call" action type uses the event object of the calling Rule as its second argument. However, this event object is set automatically by the Rule, whereas the expectation when using `_satellite.track()` is that you can send your own custom event object in the second argument.

https://github.com/adobe/reactor-extension-core/blob/213989a7d9895871c5a1640ab9dde38da7822dac/src/lib/actions/directCall.js#L27-L31

### Reproduce Scenario (including but not limited to)
See Sample Code below.

#### Steps to Reproduce
See Sample Code below.

#### Platform and Version
All

#### Sample Code that illustrates the problem
Expected usage with Direct Calls:
``{{
var detail = { name: 'John Doe' };
_satellite.track("identifier", detail); // detail is a custom event object
}}``

#### Logs taken while reproducing problem
N/A

**Comment by thebenrob** [comment]
@yuhui, currently, the same event that triggers the 1st direct call is passed through to the second.  Can you describe the use case a bit more for passing a different event object to the 2nd rule?
Should you also be able to prevent the passing of an object?  How would you expect to provide a custom event?  Data element selector?  Something else?

**Comment by Aaronius** [comment]
@thebenrob, I'll chime in here. In my opinion, it doesn't make sense to pass the event from the first rule into the second rule. The event object from the first rule contains information like the rule's name and other things that probably are not particularly useful inside the second rule. Instead, the customer should be able to provide their own object that should be passed to the second rule. I'm not as familiar with the use cases, but I know customers pass in data when they execute direct call rules quite frequently. It's kind of like calling a function with arguments. This would probably be done through either a code editor or a data element selector inside the Trigger Direct Call action type view. I would like to hear if this matches @yuhui's vision and whether he would prefer seeing a code editor or a data element selector. Part of me still wants to see a data element type that allows the customer to build an object without using code (similar to the XDM Object data element type in the AEP Web SDK extension, except not XDM-specific), because I think it could be useful in this case.

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL
